sekoia_automation/cli.py
Ruff [v0.0.253](https://github.com/charliermarsh/ruff/releases/tag/v0.0.253) removed the need to annotate `noqa` when using `Optional[str]` instead of `str | None`.
The directives can be removed.
=> fix: Remove unused directives

.github/workflows/ci.yml, codecov.yml
Sonar cloud scans cannot be performed when the PR is created from a forked repository.
For this reason this PR moves away from Sonar and relies on codecov to add a code coverage gate.
We will lose the other analysis provided by sonar.
=> chore: Swtich from sonar to codecov

CHANGELOG.md, poetry.lock, sekoia_automation/action.py, sekoia_automation/connector.py, sekoia_automation/module.py, sekoia_automation/trigger.py, tests/test_trigger.py
In some specific cases `get_data_path()` fails, because the trigger/action doesn't have access to the S3 bucket.
Currently it means:
* The trigger will be restarted over and over again without sending any logs to the API
* The action will fail but will never report back to the API
This fix:
* Don't call `get_data_path()` in the init anymore
* Add a new property `data_path` that will set `_data_path` if not set
* Make sure `_data_path` is set at the begining of the `execute` command
* It is done in order to not break modules  relying on `_data_path`
* Those modules should now use the public attribute `data_path`
Additionally this PR add new tags in sentry.
=> fix: Better handling of error on data path access

CHANGELOG.md, sekoia_automation/connector.py, sekoia_automation/module.py, sekoia_automation/trigger.py, tests/test_trigger.py
Adds a simple HTTP server with an `health` endpoint to allow external watchers to query the current health of the running trigger.
For now a traditional trigger is always considered alive, and a connector is considered alive if it sent at least an event in the last 3600 seconds.
=> feat: Add liveness HTTP endpoint

CHANGELOG.md, sekoia_automation/connector.py
Reset the error counter when pushing events to intake so the connector exits when we have 5 consecutive errors and not 5 errors in the life of the connector.
This is already done in the "regular" triggers when sending events.
=> fix: Reset error counter when pushing events to intake

sekoia_automation/connector.py, tests/test_connector.py
- Prevent option for the connector to be forwarded to the trigger
- Handle event forwarding when the executor is down to avoid events lost
=> Improve event forwarding

CHANGELOG.md, sekoia_automation/trigger.py, tests/connectors/test_connector.py
Automatically start the metrics exporter when starting the trigger (Will replace exporter instructions in connectors).
=> open a metrics exporter when the trigger starts

CHANGELOG.md, sekoia_automation/trigger.py, tests/test_trigger.py
Add graceful period in which 5 errors won't trigger a critical error, so the trigger can keep running.
This period depends on the time the trigger has been running and is limited to 24 hours.
=> feat: Add graceful period before logging a critical

sekoia_automation/action.py, tests/test_action.py
The module configuration can either be a dict or a more complex object such as OpenAIConfiguration
We added a check and in case the config is not a dict, we set the secrets using setattr
=> Fix a typing issue when adding secrets to a module

CHANGELOG.md, sekoia_automation/cli.py, sekoia_automation/scripts/sync_library.py, tests/scripts/test_sync_library.py
* Add registry information to docker images (registry and its namespace)
* Improve checking the existence of an image
* Single HTTP call
* Support public registries without credentials
=> feat: Add registry info to docker images

CHANGELOG.md, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/pyproject.toml, sekoia_automation/scripts/sync_library.py
- In `synchronize-lib` error display docker image name used previously
- In module template don't use a specific python package index
=> Fix: Minor fixes in scripts

CHANGELOG.md, sekoia_automation/connector/__init__.py, sekoia_automation/trigger.py, tests/test_trigger.py
- On critical error wait until the pod is killed instead of keep running
- Increase time to wait without events before restarting the pod
=> feat: Small improvements in triggers

CHANGELOG.md, sekoia_automation/trigger.py, tests/test_trigger.py
Send trigger logs by batch. A batch is sent if:
* An error or a critical log is received
* The batch reached 50 logs
* The first pending log has been waiting for more than 5 seconds
With this implementation a log may be waiting to be sent for more than 5 seconds if the trigger doesn't create new logs. I think it is acceptable because important logs are sent immediately and it avoid to add complexity to the code.
=> feat: Send logs by batch

CHANGELOG.md, pyproject.toml, sekoia_automation/config.py, sekoia_automation/storage.py, tests/conftest.py, tests/test_storage.py
The directory `/symphony` cannot be created from inside a docker container running with low privileges. Instead write the TLS related files under `/tmp`
=> fix: Store TLS related files in a writable storage

CHANGELOG.md, poetry.lock, pyproject.toml, sekoia_automation/scripts/files_generator.py, sekoia_automation/scripts/new_module/template/hooks/post_gen_project.sh, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/main.py, tests/data/sample_module/sample.py, tests/expectations/sample_module/connector_sample_connector.json, tests/scripts/test_files_generator.py
* Generate new module:
* Add hook to lock requirements 
* Fix module import for modules with spaces
* Generate files from code:
* Do not generate trigger manifest for connectors
=> fix: Various fixes in scripts

CHANGELOG.md, sekoia_automation/aio/connector.py
Specify module and data_path as first arguments of AsyncConnector. Otherwise, when the module starts an async connector, the module ends as the event loop and an unnamed module is instantiated as module of the connector.
=> Async: Fix arguments for AsyncConnector

CHANGELOG.md, sekoia_automation/aio/connector.py
Remove some logs, from connectors, that are redundant with existing ones in order to reduce the number of requests to the API
=> AIO: remove redundant logs.

CHANGELOG.md, sekoia_automation/connector/__init__.py
When forwarding events to sekoai.io, use a Requests' session in order to reuse existing HTTP connections (and speed up requests)
=> Connector: use HTTP session

CHANGELOG.md, sekoia_automation/aio/connector.py, sekoia_automation/aio/helpers/__init__.py
- Improve the concurrency of async tasks that forward events to intake.sekoia.io
- Add a mechanism to control the number of concurrent tasks at the same time. The purpose is to avoid overload the memory.
=> Async: Improve concurrency between forwading async tasks

sekoia_automation/scripts/new_module/template/hooks/post_gen_project.sh, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/CHANGELOG.md, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/Dockerfile, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/manifest.json, sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/tests/conftest.py
1. Include empty CHANGELOG.md
2. Get the latest version of Sekoia Automation SDK automatically
=> Improve module creation script

sekoia_automation/scripts/new_module/template/{{cookiecutter.module_dir}}/pyproject.toml
The single quote goes automatically in the virtual env's path, causing errors
=> Module generator - change default title

CHANGELOG.md, poetry.lock, pyproject.toml, sekoia_automation/scripts/documentation/generate.py, sekoia_automation/scripts/documentation/templates/module.md, tests/data/documentation/mkdocs.yml, tests/data/sample_module/manifest.json, tests/data/sample_module/trigger_test.json, tests/expectations/sample_module/manifest.json, tests/scripts/test_sync_library.py, tests/test_cli.py
Improve documentation generation:
* Add metadata to pages
* Replace XDR module pages with Integrations ones
* Specify categories for modules
=> feat: Update documentation generation command

CHANGELOG.md, sekoia_automation/scripts/sync_library.py, tests/data/sample_module/manifest.json, tests/expectations/sample_module/manifest.json, tests/scripts/test_sync_library.py
Override https://github.com/SEKOIA-IO/sekoia-automation-sdk/pull/148
=> Module Publication: fix the way to handle docker image information

CHANGELOG.md, pyproject.toml, sekoia_automation/scripts/sync_library.py, tests/scripts/test_sync_library.py
Setting value to `None` when not in the manifest is creating an issue for optional fields that can't be null, i.e. the release status
=> fix: Fixes synchronization script

CHANGELOG.md, pyproject.toml, sekoia_automation/scripts/documentation/templates/module.md
This PR allows us adding a configuration paragraph by adding a description field in the arguments section in each action_* file, if needed of course.
=> Add Configuration part

CHANGELOG.md, pyproject.toml, sekoia_automation/action.py, tests/test_action.py
This PR focuses on adding list types into the validation response.
=> Add list to validate response
